version: '3'

services:
  integration:
    build: 
      context: ./src
      dockerfile: Dockerfile
    image: dialogflow-integration
    container_name: integration-middleware
    restart: unless-stopped
    env_file:
      - ./app.env
    ports:
      - 3000:3000
