const {
    NODE_ENV,
    APP_PORT,
    APP_HOST,
    ZOKO_API_MESSAGE_URL,
    ZOKO_API_KEY,
    DIALOGFLOW_PROJECT_ID,
    DIALOGFLOW_CLIENT_EMAIL,
    DIALOGFLOW_PRIVATE_KEY,
    WEBHOOK_URL
} = process.env;

module.exports = {
    NODE_ENV,
    APP_PORT,
    APP_HOST,
    ZOKO_API_MESSAGE_URL,
    ZOKO_API_KEY,
    DIALOGFLOW_PROJECT_ID,
    DIALOGFLOW_CLIENT_EMAIL,
    DIALOGFLOW_PRIVATE_KEY,
    WEBHOOK_URL
};
